version: '3.8'
services:
  java-maven-app:
    image: sujadocker14/java-maven-app:1.0.9-11
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
